# Generated by Django 4.0.4 on 2022-05-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
